### ISSUE TITLE
please handle doc case

### ISSUE THREAD

**Issue by huang12zheng** [felixblaschke/readme_helper#2]
```dart
///
// #begin
/// final configState = StateProvider((ref) => Configuration());
// #end
///
```
=>
```
final configState = StateProvider((ref) => Configuration());
```
in place of 
 ```
/// final configState = StateProvider((ref) => Configuration());
```

**Comment by felixblaschke** [comment]
Automatic un-commenting a line of code? What is the use case?

**Comment by huang12zheng** [comment]
I have examples in my question, but maybe I'm trying to simplify.
``dart
if (line.startsWith('/// ')) {
        line = line.substring(4, line.length);
      }
```
my code is dirty

**Comment by huang12zheng** [comment]
this maybe you need
```dart
import 'dart:math';

// #begin
/// ```dart
/// //...
/// MyClass.someMethod()
/// //...
/// ```
/// // #end
class MyClass {
  // #skip
  int someMethod() {
    return Random().nextInt(1);
  }
  // #resume

  String interestingMethod() {
    return 'Foo';
  }
}
// #end
```

**Comment by felixblaschke** [comment]
Ok, you want to recycle the example, you already wrote into your dartdoc? Do I understand that correct?

**Comment by huang12zheng** [comment]
you are right.

**Comment by felixblaschke** [comment]
I have an even better idea. What if the readme_helper will also generate a dedicated example into the **dartdoc** (within your regular *.dart files)

**code_example.dart** can be used for **readme.md** and **actual_lib.dart**'s DartDoc

**Comment by huang12zheng** [comment]
I'm terribly sorry. I don't quite understand. May need an example...
this is my output
<img width="1680" alt="截屏2021-11-16 下午11 09 27" src="https://user-images.githubusercontent.com/28038074/142011151-bf02d075-1d91-4ee3-849a-aafb739353c5.png">


What are you looking for?

**Comment by huang12zheng** [comment]
I was wondering if you were as follow:
+ in xx.md
```
<!-- #dartdoc lib/config.dart configExample1 -->
\```dart
final configState = StateProvider((ref) => Configuration());
\```
<!-- // end of #dartdoc -->

```
+ in xxx.dart
```dart
/// {@readmehelper configExample1}
```

**Comment by huang12zheng** [comment]
~~if I export some top-level property in `dartdoc`, it would look like as follow:~~

```dart
final linkState = StateProvider<Link>((ref) {
  // Dependencies
  final config = ref.watch(configState);
// #skip
  // Links
  final logLink = LogLink();
// #resume
  final httpLink = HttpLink(config.apiEndpoint);
  final wsLink = WebSocketLink(
    config.wsEndpoint,
    // initialPayload: config.payload,
  );
  final splitLink = SplitLink(httpLink, wsLink);
// #skip
  // Link order --> first to last -->
  // wsLink must be after httpLink
  // final link = Link.from([logLink]);
  final link = Link.from([logLink, splitLink]);
  // Instantiate client
  // final client = Client(link: link);
  // Return client
// #resume
  return link;
});
```

~~There are `// #skip` and `// #resume` which is not a very pleasant experience~~

I finally found it bearable
